### ISSUE TITLE
Error creating directive

### ISSUE THREAD

**Issue by rshackleton** [netconstruct/generator-netconstruct#17]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: C:\Projects\generator-netconstruct\generators\directive\templates\directive.template.es6.js:2
    1| /**
 >> 2|  * <%= controllerName %> controller.
    3|  * @description The <%= controllerName %> controller
    4|  */
    5| class <%= directiveClassName %>Controller {

controllerName is not defined
    at eval (eval at <anonymous> (C:\Projects\generator-netconstruct\node_modules\ejs\lib\ejs.js:491:12), <anonymous>:11:23)
    at returnedFn (C:\Projects\generator-netconstruct\node_modules\ejs\lib\ejs.js:520:17)
    at Object.exports.render (C:\Projects\generator-netconstruct\node_modules\ejs\lib\ejs.js:332:37)
    at copy.extend.process (C:\Projects\generator-netconstruct\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:12:18)
    at applyProcessingFunc (C:\Projects\generator-netconstruct\node_modules\mem-fs-editor\lib\actions\copy.js:13:16)
    at EditionInterface.exports._copySingle (C:\Projects\generator-netconstruct\node_modules\mem-fs-editor\lib\actions\copy.js:51:16)
    at EditionInterface.exports.copy (C:\Projects\generator-netconstruct\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (C:\Projects\generator-netconstruct\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)
    at constructor.createDirective (C:\Projects\generator-netconstruct\generators\directive\index.js:110:15)
    at Object.<anonymous> (C:\Projects\generator-netconstruct\node_modules\yeoman-generator\lib\base.js:439:23)
```

**Comment by rshackleton** [comment]
Directive generation fixed
